Work05
OlegEryomin/JavaCourses pull request #4
Opened 2022-05-02 13:03 UTC by OlegEryomin

2022-05-03 04:48 UTC, efserg requested changes
Жду исправлений, оценку пока не ставлю

2022-05-03 04:48 UTC, efserg commented on src/main/java/com/geekbrains/courses/work05/Employee.java
> +    int age;
Сразу на доработку. Поля в классе должны быть приватными

2022-05-03 04:48 UTC, efserg commented on src/main/java/com/geekbrains/courses/work05/Main.java
> +            if (employees[i].age > 40) {
Нужен геттер

2022-05-05 13:13 UTC, OlegEryomin commented on src/main/java/com/geekbrains/courses/work05/Employee.java
> +    int age;
Добрый день! Исправил.

2022-05-05 13:14 UTC, OlegEryomin commented on src/main/java/com/geekbrains/courses/work05/Main.java
> +            if (employees[i].age > 40) {
Геттер добавил, цикл заменил на foreach

2022-05-05 15:32 UTC, efserg approved these changes

2022-05-05 19:56 UTC, merged